name: Sync from Bitbucket

on:
  push:
    branches: [ "main", "migration" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          ref: migration
          persist-credentials: true
          fetch-depth: 0

      - name: Add Bitbucket remote with git credential helper
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          git config --global credential.helper store
          echo "https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org" > ~/.git-credentials
          git remote add bitbucket https://ngumkellyshu@bitbucket.org/ngum123/migration-demo.git
          git fetch bitbucket
          git reset --hard bitbucket/master
      - name: Set up GitHub credentials
        run: |
          git config --global user.email "felixmomodebe0711@gmail.com"
          git config --global user.name "Felix M."
      - name: Push changes to GitHub using Personal Access Token
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://github.com/kelly-bright09/migration_demo1.git
          git push -f origin HEAD:main
      - name: Clean up Bitbucket remote
        run: git remote remove bitbucket
